apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "vm.labels" . | nindent 4 }}
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  dataVolumeTemplates:
    - metadata:
        name: {{ .Values.app.name }}-volume
      spec:
        sourceRef:
          kind: DataSource
          # UPDATE to paramaterize the RHEL version
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    name: u1.medium
  preference:
    # UPDATE to paramaterize the RHEL version
    name: rhel.9
  runStrategy: Always
  template:
    metadata:
      labels:
        {{- include "vm.labels" . | nindent 8 }}
        {{- include "backstage.labels" . | nindent 8 }}
        network.kubevirt.io/headlessService: headless   
    spec:
      domain:
        devices:
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name:  {{ .Values.app.name }}-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: 211v-rwla-c4s4
              user: rhel
          name: cloudinitdisk
